output_dir: "<insert>" # output directory for your retrieval csvs
output_suffix: "all_anomalies"
mentions_path: "<insert>.pkl" # should point to the precomputed mentions of the train retrieval reports
retrieval_mentions_path: "<insert>.pkl" # should point to the precomputed mentions of the retrieval reports
mrrel_path: "<path/to>/MRREL.RRF"
mrhier_path: "<path/to>/MRHIER.RRF"
mrconso_path: "<path/to>/MRCONSO.RRF"
mrsty_path: "<path/to>/MRSTY.RRF"
index_dir: "<insert>" # location of your SapBERT FAISS index
index_file: "<index_dir>/sapbert.index"
mapping_file: "<index_dir>/sapbert_id2cui.json"

init_data_args:
  image_base_path: "<insert>" # Main Folder of your MIMIC-CXR Image Files
  report_column: "impression"
  id_column: "dicom_id"
  image_path_column: "path"

retrieval_args:
  use_ic: False
  cost_function: sym_tversky # set to cosine_similarity to use LLMs

hyperparameters:
  k: 1
  max_expl_depth: 10
  alpha: 0.5
  beta: 1

  batch_size: 1
  max_length: 77

cosine_similarity:
  type: cxr-bert
  model: microsoft/BiomedVLP-CXR-BERT-specialized
  subfolder: False
  index_path: <insert>/cxr-bert_all_diseases.index # path to the LLM FAISS index (see knowledge_graph/similarity_search.py)
