output_dir: "/vol/ideadata/ce90tate/knowledge_graph_distance/retrieved_final/"
output_suffix: "all_anomalies"
mentions_path: "/vol/ideadata/ce90tate/data/umls/mentions_mimic_lt_train_retrieval_top128_all_diseases.pkl"
retrieval_mentions_path: "/vol/ideadata/ce90tate/data/umls/mentions_8_balanced_retrieve_retrieval_top128_all_diseases.pkl"
mrrel_path: "/vol/ideadata/ce90tate/data/umls/2024AB/META/MRREL.RRF"
mrhier_path: "/vol/ideadata/ce90tate/data/umls/2024AB/META/MRHIER.RRF"

init_data_args:
  image_base_path: "vol/ideadata/ed52egek/data/mimic/jpg/physionet.org/files/mimic-cxr-jpg/2.0.0/"
  report_column: "impression"
  id_column: "dicom_id"
  image_path_column: path

retrieval_args:
  use_ic: False
  cost_function: sym_tversky

hyperparameters:
  k: 1
  max_expl_depth: 10
  alpha: 0.5
  beta: 1

  batch_size: 1
  max_length: 77

cosine_similarity:
  type: cxr-bert
  model: microsoft/BiomedVLP-CXR-BERT-specialized
  subfolder: False
  index_path: /vol/ideadata/ce90tate/data/faiss/ss/cxr-bert_all_diseases.index
